### ISSUE TITLE
Doesn't save new project

### ISSUE THREAD

**Issue by davidemasserini** [projectknife/pkg-projectknife#1]
I try to create a new Project but it doesn't work.
![createnew](https://cloud.githubusercontent.com/assets/3454665/19074671/97e37dc6-8a41-11e6-833f-a2a66070cc89.gif)
I have Joomla 3.6.2, PHP 5.6.

**Comment by eaxs** [comment]
I've tested on Joomla 3.6.2 and PHP 5.6 just now and it works fine for me. Maybe problem is somewhere else. Can you create a project in the frontend? I assume you've tried this as Super Admin, right?

You could check out the PHP error log, it might have something useful to say. Otherwise you should try the next alpha release where a lot of code has changed again. Maybe it has already been fixed.

**Comment by dmware** [comment]
I created a menu item Projectknife - Dashboard and this is what I see :) https://www.dmware.it/project-knife which is basically nothing :)

**Comment by eaxs** [comment]
Yes, the dashboard is currently just empty. When you installed projectknife, it should have created a menu and a module on position 7 for you:
![pkmodpos](https://cloud.githubusercontent.com/assets/489521/19075952/47d938e2-8a47-11e6-856e-6ed0e7e457ba.jpg)

You may need to change their position in order to see the them on the site.

**Comment by eaxs** [comment]
If you like, you can try installing the latest dev code by downloading and installing:
https://github.com/projectknife/pkg-projectknife/archive/dev.zip

Before you can do that however, you have to delete your current Projectknife installation. It's very simple though. In the Joomla backend go to: Extensions > Manage > Manage > Search Tools Filter Type: "Package"  > Uninstall Projectknife package.

And then you can install the dev code. Let me know if the issue still exists there, thanks!

**Comment by dmware** [comment]
Thanks, well, now it's worste, I don't see the template anymore :) https://www.dmware.it/project-knife - I guess I'll wait for a more stable version.

**Comment by eaxs** [comment]
Ah the build is broken, sorry :( The next release is coming this week anyway. Just have to wrap up some changes to the permissions.
