### ISSUE TITLE
languages packages

### ISSUE THREAD

**Issue by learnmeup** [projectknife/pkg-projectknife#25]
Hello,
Where could I find French language packages for projectknife ?
Is there any translation project ?
Best regards,
Arnaud

**Comment by eaxs** [comment]
We currently don't have any translations available, but we are working on adding a translation management system to our website, so that volunteers can help translating Projectknife and all the extensions. 

We hope to have it done by the end of the month, and then we can also automatically import a lot of what was previously translated for Projectfork 4.

**Comment by gigarun** [comment]
when it's donne ; i will buy full access. but at this point, not interesting without french !

**Comment by learnmeup** [comment]
Hi eaxs, thanks for your answer. I will have a look to the translation management system, and will help, if I can. Regards.

**Comment by learnmeup** [comment]
Hi gigarun, I'm waiting for the French translation too, but I purchased the product to support the editor. For information, translation of the former version of the product was pretty good. Regards.
